### ISSUE TITLE
BQ25896

### ISSUE THREAD

**Issue by asenelupinn** [andhieSetyabudi/BQ25896#1]

**Comment by andhieSetyabudi** [comment]
hello @ngohoan98 
can i help you ?

**Comment by ngohoan98** [comment]
I am a student just beginning to learn about programming. I am stuck in the library of BQ25892 for stm32f103c8t6, I don't know where to start. Can you help me?

**Comment by andhieSetyabudi** [comment]
are you using bluepill? 
BQ25896 is battery-management system ( charging ) that use I2C for communication line.
so u can wiring sda & scl from STM32F103 to BQ chip. 

create the obj by calling

BQ25896  battery_charging(Wire);

to update properties of your measurement, use

battery_charging.properties(); 

or you can try to type a program, same as in readme

**Comment by asenelupinn** [comment]
thank you so much
