### ISSUE TITLE
Wrong address 

### ISSUE THREAD

**Issue by Mala2** [andhieSetyabudi/BQ25896#3]
on the .h file, the address was 0x6b while the correct one is 0x6a. 
please check:https://e2e.ti.com/support/power-management/f/196/t/507682?BQ25895-I2C-Address-and-I2c-voltage

Anyway, I changed it to 0x6a and everything seems to work fine. Thanks a lot for your work

**Comment by andhieSetyabudi** [comment]
Thanks for the information.. 
I've updated it..
